[dependencies]
arrayvec = { default-features = false, optional = true, version = "0.5" }
cl-traits = { features = ["alloc"], version = "1.0" }
futures = { default-features = false, features = ["alloc"], optional = true, version = "0.3" }
mop-common-defs = { path = "../mop-common-defs", version = "0.0.10" }
ndsparse = { optional = true, version = "0.5" }
num-traits = { default-features = false, features = ["libm"], version = "0.2" }
rand = { default-features = false, features = ["getrandom"], optional = true, version = "0.7" }
serde = { default-features = false, features = ["derive"], optional = true, version = "1.0" }

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"

[features]
default = []
std = ["arrayvec/std", "cl-traits/std", "futures/std", "mop-common-defs/std", "ndsparse/std", "num-traits/std", "rand/std", "serde/std"]
with_arrayvec = ["arrayvec", "cl-traits/with_arrayvec", "ndsparse/with_arrayvec"]
with_futures = ["futures", "mop-common-defs/with_futures"]
with_ndsparse = ["ndsparse"]
with_rand = ["ndsparse/with_rand", "rand"]
with_serde = ["arrayvec/serde", "cl-traits/with_serde", "ndsparse/with_serde", "rand/serde1", "serde"]

[package]
authors = ["Caio Fernandes <c410.f3r@gmail.com>"]
description = "Foundation blocks for MOP"
edition = "2018"
keywords = ["mop"]
license = "Apache-2.0"
name = "mop-blocks"
readme = "README.md"
repository = "https://github.com/c410-f3r/mop"
version = "0.0.10"
